BEGIN TRANSACTION;
CREATE TABLE "demo_incident" ("accident_pk" TEXT,"accident_no" TEXT,"accident_title" TEXT,"city_name" TEXT,"line_name" TEXT,"registered_lot_count" INTEGER);
INSERT INTO "demo_incident" VALUES('PK001','INC-001','외곽 Shot Fail','화성','65L (ABCD)',6);
INSERT INTO "demo_incident" VALUES('PK002','INC-002','Shot 반복 Fail','화성','65L (ABCD)',4);
INSERT INTO "demo_incident" VALUES('PK007','INC-007','현상 잔류 패턴','화성','65L (ABCD)',1);
INSERT INTO "demo_incident" VALUES('PK009','INC-009','연결 누락 확인 예시','평택','67L (MNOP)',2);
CREATE TABLE "demo_lot_list" ("accident_ref" TEXT,"lot_no" TEXT,"product_name" TEXT,"lot_state" TEXT);
INSERT INTO "demo_lot_list" VALUES('PK001','LOT-001','PX_B','REGISTERED');
INSERT INTO "demo_lot_list" VALUES('PK001','LOT-002','PX_C','REGISTERED');
INSERT INTO "demo_lot_list" VALUES('PK001','LOT-003','PX_B','REGISTERED');
INSERT INTO "demo_lot_list" VALUES('PK001','LOT-004','PX_C','REGISTERED');
INSERT INTO "demo_lot_list" VALUES('PK001','LOT-005','PX_B','REGISTERED');
INSERT INTO "demo_lot_list" VALUES('PK001','LOT-006','PX_C','REGISTERED');
INSERT INTO "demo_lot_list" VALUES('PK002','LOT-006','PX_C','REGISTERED');
INSERT INTO "demo_lot_list" VALUES('PK002','LOT-007','PX_B','REGISTERED');
INSERT INTO "demo_lot_list" VALUES('PK002','LOT-008','PX_C','REGISTERED');
INSERT INTO "demo_lot_list" VALUES('PK002','LOT-009','PX_B','REGISTERED');
INSERT INTO "demo_lot_list" VALUES('PK007','LOT-010','PX_C','REGISTERED');
INSERT INTO "demo_lot_list" VALUES('PK001','LOT-001','PX_B','REGISTERED');
COMMIT;